README.md
1. Fix syntax highlighting in examples (use `console` not `shell`).
2. Minor punctuation nits.
=> README.md: nits

lib/metadata.go
When Podman is running a container in private IPC mode (default), it creates a bind mount for `/dev/shm` that is attached to a tmpfs folder on the host file system. However, checkpointing a container has the side-effect of stopping that container and unmount the tmpfs used for `/dev/shm`. As a result, after checkpoint all files stored in the container's `/dev/shm` would be lost and the container restore might fail.
To address this problem, this commit defines a metadata tar file that could be used to store the content of `/dev/shm`, include it in the container checkpoint, and restore it.
=> metadata: Add DevShmCheckpointTar

checkpointctl.go, container.go, test/checkpointctl.bats, test/spec.dump
The `checkpointctl` tool could be extended  to display an overview of mounts used by the checkpoints. 
This pull request adds  `--mounts` option for the `checkpointctl show` command, which would extend the *out* to look like this:
```
checkpointctl show checkpoint.tar.gz --mounts
Displaying container checkpoint data from /tmp/checkpointctl1209302006
+----------------+--------------------------------+--------------+---------+---------------------------+--------+------------+-------------------+
|   CONTAINER    |             IMAGE              |      ID      | RUNTIME |          CREATED          | ENGINE | CHKPT SIZE | ROOT FS DIFF SIZE |
+----------------+--------------------------------+--------------+---------+---------------------------+--------+------------+-------------------+
| …
```
=> Add '--mounts' option

.github/workflows/tests.yml, .gitignore, Makefile
As bats supports creating junit compatible output, this output can be used to show an overview about test results directly in GitHub PRs as a comment.
=> Show test results in GitHub PRs

README.md, checkpointctl.go, test/checkpointctl.bats
This pull request adds an alias for the `--print-stats` option, to be changed to `--stats` to maintain consistency among option names of `checkpointctl show`.
Also, an `-all` option is added to display all additional information about the available checkpoints, which would extend the *out* to look like: 
```
checkpointctl show checkpoint.tar.gz --all
Displaying container checkpoint data from /tmp/checkpointctl1209302006
+----------------+--------------------------------+--------------+---------+---------------------------+--------+------------+-------------------+
|   CONTAINER    |             IMAGE              |      ID      | RUNTIME |          CREATED          | ENGINE | CHKPT SIZE | ROOT FS DIFF SIZE |
+----------------+--------------------------------+--------------+---------+------ …
```
=> Add alias and '--all' option to checkpointctl show

checkpointctl.go, container.go
And not the name of the unpacked temporary directory.
=> Show name of actual checkpoint archive

.github/workflows/check-size.yml, test/check-size.sh
This job checks the difference in binary size across commits in a PR, and fails if the difference is more than a set maximum limit. This allows us to detect early on if there is any possible bloating in the binary due to poorly structured dependencies. The job can be overridden by adding a `bloat-ok` label to the PR.
=> ci: add job to check increase in binary size

.github/workflows/check-size.yml, test/check-size.sh
The workflow fails during rebase since git cannot find any details of a user to create the commits. This adds a dummy user to fix this.
=> fix(ci): set git credentials for rebase

checkpointctl.go, container.go
The logic for rendering tables with the checkpoint data was all present
in a single function `showContainerCheckpoint()`. This has now been
refactored to provide each table its own function that can be called to
render it. This increases code maintainability going forward as more and
more tables are added to the `checkpointctl show` command.
=> refactor: move table rendering into own funcs

.github/workflows/check-size.yml, test/check-size.sh
This pull request adds an error message when compilation fails when running the `check-size.sh` script.
=> test/check-size: show error if make fails

checkpointctl.go, container.go, go.mod, go.sum, test/checkpointctl.bats, vendor/github.com/xlab/treeprint/.gitignore, vendor/github.com/xlab/treeprint/LICENSE, vendor/github.com/xlab/treeprint/README.md, vendor/github.com/xlab/treeprint/helpers.go, vendor/github.com/xlab/treeprint/struct.go, vendor/github.com/xlab/treeprint/treeprint.go, vendor/modules.txt
CRIT already allows us to explore the process tree, file descriptors, memory map, and RSS map for a checkpoint. These features can be integrated with checkpointctl to allow more info to be displayed with `checkpointctl show`. This PR introduces `checkpointctl show --ps-tree` for viewing the process tree.
Here's a sample output of the tree displayed for a single process:
```
Process tree
Container
└── [1]  piggie
```
=> feat: add flag to view process tree

.github/workflows/check-size.yml
We were previously using the merge commit as the baseline, leading to all commits from the pull request being rebased, rather than just the latest commit.
=> fix(ci/check-size): use latest non-merge commit

container.go
The recursive logic used to process nodes in the process tree was accidentally appending child nodes twice. This has been fixed by removing the addition of the extra node at the same depth before processing the child.
Fixes #70
=> fix: remove redundant nodes in process tree

.github/workflows/tests.yml, Makefile
This pull request modifies the Makefile to build a static `checkpointctl` binary and eliminate dependency on dynamic libraries. This change ensures that the resulting binary can be effortlessly distributed and executed across various systems and linux distributions. For example, a binary built on a Fedora system will seamlessly run on Ubuntu and vice versa.
=> Build static checkpointctl binary for improved portability

checkpointctl.go, container.go, test/checkpointctl.bats
This commit enhances the functionality of the "show" command by enabling it to list multiple checkpoint archives.
Examples:
```bash
$ls checkpoints/
nginx-checkpoint.tar.gz  ubuntu_multiuser.tar.gz
$checkpointctl nginx-checkpoint.tar.gz  ubuntu_multiuser.tar.gz
+----------------+---------------------------------+--------------+---------+---------------------------+--------+----+-----+------------+-------------------+
|   CONTAINER    |              IMAGE              |      ID      | RUNTIME |          CREATED          | ENGINE | IP | MAC | CHKPT SIZE | ROOT FS DIFF SIZE |
+----------------+---------------------------------+--------------+---------+---------------------------+--------+----+-----+------------+-------------------+
| awesome_booth  | docker.io/library/ubuntu:latest | …
```
=> show: add support for listing multiple checkpoints

checkpointctl.go
The `print-stats` flag was deprecated in `checkpointctl show`, and need not be introduced as a legacy flag in `checkpointctl inspect`.
=> chore: remove extra deprecated flag

test/checkpointctl.bats, tree.go
The overview of mounts used in container checkpoint is likely to be more than 30 lines. In comparison, the output for checkpoint statistics and process tree are likely to take less space. To improve readability, this patch moves the mounts overview at the end of the output of `inspect --all`.
Before:
```
looper
├── Image: docker.io/library/busybox:latest
├── ID: 03be7aa1b3aa16a46fff2882840afcd192d0f5c7ef79bb8d02f9a846920327cf
├── Runtime: crun
├── Created: 2023-07-10T12:48:11+01:00
├── Engine: Podman
├── Checkpoint size: 154.5 KiB
├── Overview of mounts
│   ├── Destination: /proc
│   │   ├── Type: proc
│   │   └── Source: proc
│   ├── Destination: /dev
│   │   ├── Type: tmpfs
│   │   └── Source: tmpfs
│   ├── Destination: /sys
│   │   ├── Type: sysfs
│   │   └── Source: sysfs
│   ├── …
```
=> tree: show mounts after pstree

checkpointctl.go, test/checkpointctl.bats, tree.go
Currently, the entire process tree is rendered in the tree view. This allows for the tree to be pruned for a specific process using the `--pid` or `-p` flag.
Fixes #86
=> feat: filter by PID in process tree

checkpointctl.go, container.go, test/checkpointctl.bats, tree.go
This PR introduces a new flag `--ps-tree-cmd` to provide an alternative view of process tree.  
Using `--ps-tree-cmd`  it is now possible to display the full command line arguments in the process tree.
Example:
```bash
$ checkpointctl inspect /path/to/checkpoint.tar.gz --ps-tree-cmd
counter
└── [1]  bash
├── [7]  bash -c 'python counter.py'
├── [8]  python counter.py --input data.txt --output result.txt
├── [11]  bash -c 'tee output.log'
└── [20]  tee output.log
```
=> feat: display process tree with command line arguments

checkpointctl.go, container.go, test/checkpointctl.bats, tree.go
This commit introduces a new flag, --ps-tree-env, which enables the display of process environment variables in the process tree output.
Example output:
```bash
$ checkpointctl inspect --ps-tree-cmd /path/to/checkpoint.tar.gz 
Displaying container checkpoint tree view from /home/behouba/checkpoints/httpd.tar.gz
httpd
├── Image: docker.io/library/httpd:2.4
├── ID: 4f6831a7e8e641e75578704cb90bcbd987b6d9655404b58f5cbf954d042f3212
├── Runtime: crun
├── Created: 2023-07-22T13:14:49+03:00
├── Engine: Podman
├── Checkpoint size: 5.2 MiB
├── Root FS diff size: 2.0 KiB
└── Process tree
└── [1]  httpd
├── HTTPD_VERSION=2.4.57
├── HOSTNAME=4f6831a7e8e6
├── HOME=/root
├── HTTPD_PATCHES=rewrite-windows-testchar-h.patch 1d5620574fa03b483262dc5b9a66a6906553389952ab5d3070a02f887cc20193
├── …
```
=> feat: display process tree with environment variables

checkpointctl.go, test/checkpointctl.bats
This patch enables `--ps-tree-cmd` and `--ps-tree-env` options when the `inspect` command is used with `--all`. This change provides more complete information about the processes included in a container checkpoint.
=> inspect: enable --ps-tree-{env,cmd} with --all

Makefile, tree.go, utils.go, utils_test.go
This pull request transforms the CRIU statistics into human-readable format.
Example:
```
httpd
├── Image: docker.io/library/httpd:2.4
├── ID: 04b6be846ef4535bf9027ae36b7f3efeda78f2c314c4d9694b09da70db042b88
├── Runtime: crun
├── Created: 2023-08-07T13:02:38+01:00
├── Engine: Podman
├── Checkpoint size: 5.2 MiB
├── Root FS diff size: 2.0 KiB
└── CRIU dump statistics
├── Freezing time: 3.781 ms
├── Frozen time: 116.54 ms
├── Memdump time: 22.666 ms
├── Memwrite time: 3.382 ms
├── Pages scanned: 1498870
└── Pages written: 1213
```
=> stats: use time units in human-friendly format

README.md, checkpointctl.go, memparse.go, test/checkpointctl.bats, tree.go
This PR introduces a new sub-command `memparse` ,  which allows analyzing processes memory pages. 
This new feature was discussed here #69. 
When used without any arguments, the command displays a table showing the memory sizes of processes. Here's an example:
```bash
$ checkpointctl memparse /path/to/checkpoints/jira.tar.gz 
Displaying processes memory sizes from /home/behouba/checkpoints/jira.tar.gz
+-----+--------------+-------------+
| PID | PROCESS NAME | MEMORY SIZE |
+-----+--------------+-------------+
|   1 | tini         | 100.0 KiB   |
+-----+--------------+-------------+
|   2 | java         | 553.5 MiB   |
+-----+--------------+-------------+
```
If a process ID (pid) is provided, the command prints the memory pages of that specific process in a hexdump-like format. For …
=> feat: add `memparse` sub-command

container.go, lib/metadata.go, test/checkpointctl.bats, tree.go
This pull request extends the `checkpointctl inspect` command to display the size of memory pages and GPU memory as sub-nodes of *checkpoint size*.
Example:
```
rocm-matrix-multiplication-container
├── Image: quay.io/radostin/rocm-matrix-multiplication:latest
├── ID: 453745dcea71ec3a303242a44452b60118d8be1a3aa9a2cf8c6cae1aaf9855f4
├── Runtime: runc
├── Created: 2023-08-11T09:45:00.63222499+01:00
├── Engine: CRI-O
├── IP: 10.85.0.12
├── Checkpoint size: 28.4 GiB
│   ├── Memory pages size: 28.3 GiB
│   └── AMD GPU memory pages size: 140.1 MiB
└── Root FS diff size: 2.5 KiB
```
```
jira
├── Image: docker.io/atlassian/jira-software:latest
├── ID: 3f731c3a3951e25cc6509a3d49d7e8b799dc14dec4a96abb95e1ece55fb1692c
├── Runtime: crun
├── Created: 2023-08-11T10:24:48+01:00
├── Engine: Podman
├── …
```
=> inspect: show size of memory pages

checkpointctl.go, test/checkpointctl.bats, tree.go
This is now supported with the `--sockets` flag.
=> feat: display sockets in process tree

checkpointctl.go, go.mod, go.sum, memparse.go, vendor/github.com/checkpoint-restore/go-criu/v6/crit/mempages.go, vendor/modules.txt
This PR add a new column to the `memparse` table, which displays the shared memory size of each process within the checkpoint.
Example:
```bash
Displaying processes memory sizes from /tmp/checkpoints/mysql.tar.gz
+-----+--------------+-------------+--------------------+
| PID | PROCESS NAME | MEMORY SIZE | SHARED MEMORY SIZE |
+-----+--------------+-------------+--------------------+
|   1 | mysqld       | 349.7 MiB   | 188.0 KiB          |
+-----+--------------+-------------+--------------------+
```
=> memparse: show process shared memory size

tree.go
In some cases, processes may remove all environment variables inherited from the parent process (e.g., [nginx](https://nginx.org/en/docs/ngx_core_module.html#env)). This pull request adds a conditional statement to show the environment variables tree branch only when necessary.
=> tree: skip empty env variables branch

checkpointctl.go, json.go, json_test.go
=> Extend inspect output format with json

.github/workflows/coverage.yml, .github/workflows/tests.yml, json.go, test/Makefile, test/checkpointctl.bats, test/piggie/piggie.c
This pull request adds a test case that verifies the output JSON format for checkpointctl.
=> test: add e2e test for json format

internal/container.go, internal/json.go, internal/tree.go, test/checkpointctl.bats
This fixes containerd archive created time handling and adds checkpointed time for all archives.
=> Handle time stamps from containerd checkpoint archives

checkpointctl.go, cmd/list.go, docs/checkpointctl-list.adoc, internal/config_extractor.go, internal/config_extractor_test.go, lib/metadata.go, test/checkpointctl.bats, test/data/list_config_spec.dump/config.dump, test/data/list_config_spec.dump/spec.dump
=> Add support for list command to get the list of container checkpoints

go.mod, go.sum
This PR runs `make vendor` to update the project's dependencies, as we encountered unexpected test failures in #127
=> Run `make vendor` to update dependencies due to go version change

lib/metadata.go
containerd structures the internal metadata differently. For a restore the status.dump file is also necessary.
=> Additional container metadata from containerd

Makefile
The `check-go-version` Makefile target was introduced to verify that the Go version is at least 1.20 before running tests with code coverage. However, the minimum version of Go required by checkpointctl has been updated recently to 1.21 and the `check-go-version` target is no longer needed.
=> make: drop check-go-version target

internal/tree.go, test/checkpointctl.bats
Without this patch the output used to look something like this
```
│   └── [1]  bash
│       ├── Environment variables
│       ├── [8]  /usr/bin/coreutils
│       │   ├── Environment variables
│       │   └── Open files
│       │       └── [root]  /
│       ├── [7]  /usr/bin/python3
│       │   ├── Environment variables
│       │   ├── Open files
│       │   │   └── [root]  /
│       │   └── Open sockets
│       │       └── [TCP (LISTEN)]  0.0.0.0:8088 -> 0.0.0.0:0 (↑ 16.0 KB ↓ 128.0 KB)
│       └── Open files
│           └── [root]  /
```
Which is wrong as the list of open files (and sockets) for the first
process is after the child processes. With this change the order is now
correct:
```
│   └── [1]  bash
│       ├── Environment variables
│       ├── Open files
│       │   └── [root] …
```
=> Fix location of Open Files in tree
